name: polypodium_server
description: Sync server for Polypodium plant tracking app
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^3.0.0
  dart_jsonwebtoken: ^2.4.0
  bcrypt: ^1.1.3
  uuid: ^4.4.0
  path: ^1.9.0
  polypodium_core:
    git:
      url: https://github.com/bruno1pb13/polypodium_core.git
      ref: v0.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mocktail: ^1.0.0
